version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/website #where to store the artifacts
hooks:
  AfterInstall:
    - location: scripts/build.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user
